inherit_from: .rubocop_todo.yml

require:
  - standard

plugins:
  - rubocop-rails

inherit_gem:
  standard: config/base.yml

AllCops:
  TargetRubyVersion: 3.2
  NewCops: enable
  Exclude:
    - 'vendor/**/*'
    - 'db/schema.rb'
    - 'tmp/**/*'
    - 'bin/**/*'
    - 'config/initializers/new_framework_defaults_*'

Rails/UnknownEnv:
  Environments:
    - production
    - staging
    - development
    - test
    - e2e

Rails/EagerEvaluationLogMessage:
  Enabled: false
  Severity: warning

Rails/SquishedSQLHeredocs:
  Enabled: false

Rails/RedundantTravelBack:
  Enabled: false

Rails/RootPathnameMethods:
  Enabled: false

Rails/FilePath:
  Enabled: false

Rails/LexicallyScopedActionFilter:
  Enabled: true
  Exclude:
    - 'app/controllers/v1/**/*'

Rails/SkipsModelValidations:
  Enabled: false

Rails/HasManyOrHasOneDependent:
  Enabled: false

Rails/HasAndBelongsToMany:
  Enabled: false

# have a mixed feeling about this style
Rails/WhereRange:
  Enabled: false

Rails/Blank:
  Enabled: false
