version: "3.8"
services:
  redis:
    image: redis:7.2.4-alpine
    ports:
      - "${REDIS_PORT}:6379"
  db:
    image: postgis/postgis:12-3.1-alpine
    container_name: postgres_fti_api
    environment:
      POSTGRES_HOST_AUTH_METHOD: trust
    ports:
      - '${POSTGRES_PORT_5432_TCP_PORT}:5432'
    volumes:
      - fti_api_db:/var/lib/postgresql/data

volumes:
  fti_api_db:
