default: &default
  adapter: postgis
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  username: <%= ENV['POSTGRES_USER'] %>
  password: <%= ENV.fetch("POSTGRES_PASSWORD") { } %>
  # please see the update below about using hostnames to
  # access linked services via docker-compose
  host: <%= ENV['POSTGRES_PORT_5432_TCP_ADDR'] %>
  port: <%= ENV['POSTGRES_PORT_5432_TCP_PORT'] %>

development:
  <<: *default
  database: <%= ENV.fetch("POSTGRES_DATABASE") { "fti_development" } %>

test:
  <<: *default
  database: fti_test

e2e:
  <<: *default
  database: fti_e2e

staging:
  <<: *default
  database: fti_api_staging
  username: <%= ENV['SC_DATABASE_USER'] %>
  password: <%= ENV['SC_DATABASE_PASSWORD'] %>

production:
  <<: *default
  database: fti_api_production
  username: <%= ENV['SC_DATABASE_USER'] %>
  password: <%= ENV['SC_DATABASE_PASSWORD'] %>
