default: &default
  adapter: postgis
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  username: <%= ENV["POSTGRES_USER"] %>
  password: <%= ENV["POSTGRES_PASSWORD"] %>
  # please see the update below about using hostnames to
  # access linked services via docker-compose
  host: <%= ENV['POSTGRES_HOST'] %>
  port: <%= ENV['POSTGRES_PORT'] %>

development:
  <<: *default
  database: <%= ENV.fetch("POSTGRES_DATABASE") { "fti_development" } %>

test:
  <<: *default
  database: fti_test<%= ENV['TEST_ENV_NUMBER'] %>

e2e:
  <<: *default
  database: fti_e2e

staging:
  <<: *default
  database: fti_api_staging

production:
  <<: *default
  database: fti_api_production
