name: Linters

on: push

jobs:
  linters:
    runs-on: ubuntu-24.04

    steps:
      - uses: actions/checkout@v7
      - uses: ./.github/actions/setup-ruby-env
      - name: Run RuboCop
        run: bundle exec rubocop
